packages:
  - packages/**
  - apps/**
  - tools/**
  - '!**/test/**'
  - '!**/dist/**'

catalog:
  '@biomejs/biome': 2.3.8
  '@hono/node-server': ^1.19.0
  '@hono/zod-validator': ^0.7.2
  '@orpc/client': ^1.8.2
  '@orpc/react-query': ^1.8.2
  '@orpc/server': ^1.8.2
  '@storybook/addon-a11y': 10.1.8
  '@storybook/addon-docs': 10.1.8
  '@storybook/addon-links': 10.1.8
  '@storybook/addon-themes': 10.1.8
  '@storybook/react': 10.1.8
  '@storybook/react-vite': 10.1.8
  '@tailwindcss/vite': ^4.1.12
  '@tanstack/react-query': ^5.85.5
  '@tanstack/react-router': 1.141.6
  '@tanstack/react-router-devtools': 1.141.6
  '@tanstack/router-plugin': 1.141.6
  '@testcontainers/postgresql': ^11.9.0
  '@types/node': ^24.9.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^5.0.1
  amaro: ^1.1.4
  better-auth: ^1.3.9
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  hono: ^4.9.2
  lucide-react: 0.555.0
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  pg: ^8.16.3
  pino: ^10.0.0
  pino-pretty: 13.1.3
  react: 19.2.1
  react-dom: 19.2.1
  sonner: 2.0.7
  storybook: 10.1.8
  stripe: ^18.4.0
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  testcontainers: ^11.5.1
  tw-animate-css: ^1.3.7
  typescript: ^5.9.2
  uuid: 13.0.0
  vite: ^7.1.3
  vite-plugin-top-level-await: 1.6.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.0
  zod: 4.1.13
  zustand: ^5.0.8

onlyBuiltDependencies:
  - '@swc/core'
  - unrs-resolver
